### ISSUE TITLE
Tab滑动切换 

### ISSUE THREAD

**Issue by fuhangyy** [fuhangyy/Blog#7]
#### Tab的滑动切换原理：
首先添加一个默认的滑动块move，然后获取到当前点击的DOM的index值，最后给滑动块添加动画，移动的距离就是滑动块的宽度乘以index的值。详细操作参考代码:

```css
.contain{
  width: 400px;
  height: 60px;
  position: relative;
}
.contain ul{
  list-style: none;
  margin: 0;
  padding: 0;
  text-align: center;
}
.contain ul li{
  float: left;
  width: 80px;
}
.contain .move{
  transition: all .3s;
  position: absolute;
  width: 80px;
  height: 10px;
  top: 20px;
  left: 0px;
  background: red;
}
```

```html
<div class="contain">
  <ul>
    <li>1</li>
    <li>2</li>
    <li>3</li>
    <li>4</li>
    <li>5</li>
  </ul>
  <!-- 滑动块 -->
  <div class="move"></div>
</div>
```

```js
<script src="http://libs.baidu.com/jquery/2.0.0/jquery.min.js"></script>
<script>
  (function () {
    function Move() {
      if (!(this instanceof Move)) {  // 这里的判断时为了防止在调用Move构造函数时，忘记使用new操作符
        return new Move();            // 如果没有使用new操作符调用，此时的this是指向window的，所以这里可以提前避免给全局添加多余的属性
      }
      this.dom = '.contain';
      this.event = 'click';
      this.width = '80';
      this.getIndexAndMove();
    }
    Move.prototype = {   // 没调用一次构造函数都会为实例添加一个指向最初原型对象的ptototype指针
      constructor: Move, // 由于重写了构造函数的原型对象，会切断实例与最初原型对象的联系
      getIndexAndMove: function () {
        var that = this;  // 这里的this指向Move实例对象
        $('body').on(that.event, that.dom + ' ul li', function () {
          var $that = $(this),  // 这里的this指向当前点击的Dom对象
          $moveDom = $that.parents(that.dom).find('.move'),
          $index = $that.index();
          $moveDom.css('left', that.width * $index + 'px');	
        })		
      }
    }
    Move();
  })()
</script>
```
